# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Welcome to the official Anti-Thot Defense Force website
email: gf3869@s.maynard.k12.ma.us
description: > # this means to ignore newlines until "baseurl:"
  Our mission is to get rid of the thots.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://maynard-schools.github.io/jekyll-setup-gf3869/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# just leave someone empty to disable it
# google_analytics: 
disqus_shortname:

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->
